// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWDkeH8ytQJuvtpyHhxQwxiRLsUmXDatA',
    appId: '1:270828091134:android:e1e1be3046ed850b5257af',
    messagingSenderId: '270828091134',
    projectId: 'prove-me-wrong-bf764',
    databaseURL: 'https://prove-me-wrong-bf764-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prove-me-wrong-bf764.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH3RCW6qoxQIaWC-15yyTvwZXOw-AtMmQ',
    appId: '1:270828091134:ios:9f8263e83416d76c5257af',
    messagingSenderId: '270828091134',
    projectId: 'prove-me-wrong-bf764',
    databaseURL: 'https://prove-me-wrong-bf764-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prove-me-wrong-bf764.firebasestorage.app',
    iosBundleId: 'com.example.proveMeWrong',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWYlakJ-O_BDRA7HG6naHq3gYa2p64lAs',
    appId: '1:270828091134:web:7348075c4d4247675257af',
    messagingSenderId: '270828091134',
    projectId: 'prove-me-wrong-bf764',
    authDomain: 'prove-me-wrong-bf764.firebaseapp.com',
    databaseURL: 'https://prove-me-wrong-bf764-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prove-me-wrong-bf764.firebasestorage.app',
    measurementId: 'G-51YB71NEZ6',
  );

}